energywebfoundation/ddhub-client-gateway

libs/ddhub-client-gateway-frontend/ui/core/src/components/Table/Table.tsx

temporary disable table search

fix(ui-core): disable table backend search

---

libs/ddhub-client-gateway-frontend/ui/channels/src/lib/containers/modals/Create/Restrictions/Restrictions.effects.ts

https://energyweb.atlassian.net/browse/AEMO-431

fix(ddhub-client-gateway-ui-channels): fix open update modal error

---

libs/ddhub-client-gateway-frontend/ui/messaging/src/lib/containers/DataMessagingUpload/DataMessagingUpload.effects.ts

https://energyweb.atlassian.net/browse/AEMO-402

fix(ddhub-client-gateway-ui-messaging): silent failing file upload for large data

---

libs/ddhub-client-gateway-frontend/ui/channels/src/lib/containers/modals/Update/Update.effects.tsx
libs/ddhub-client-gateway-frontend/ui/channels/src/lib/containers/modals/Update/Update.tsx

https://energyweb.atlassian.net/browse/AEMO-426

fix(ddhub-client-gateway-ui-channels): next instead of save for restriction when updating

---

.github/workflows/master.yml
.github/workflows/publish-build.yml
devops/helms/ddhub-gateway-demo/values.yaml
devops/helms/ddhub-gateway-dev/Chart.yaml
devops/helms/ddhub-gateway-dev/frontend-values.yaml
devops/helms/ddhub-gateway-dev/values.yaml

Reverts energywebfoundation/ddhub-client-gateway#31

Revert "fix(devops): fix UI image tag reference"

---

libs/ddhub-client-gateway-frontend/ui/api-hooks/src/lib/topics/getTopicBySearch.ts
libs/ddhub-client-gateway-frontend/ui/api-hooks/src/lib/topics/getTopics.ts
libs/ddhub-client-gateway-frontend/ui/topics/src/lib/components/Topics/Topics.effects.ts
libs/ddhub-client-gateway-frontend/ui/topics/src/lib/components/Topics/Topics.tsx
libs/ddhub-client-gateway-frontend/ui/topics/src/lib/containers/modals/CreateTopic/CreateTopic.effects.ts
libs/ddhub-client-gateway-frontend/ui/topics/src/lib/models/validationSchema.ts

Changes:
1. Add loading when using search topic (backend search)
2. Prevent bad request when creating topic by setting tags as [] and enforce schema as required.

Fix/create topic UI validation

---

apps/dsb-client-gateway-api/src/app/modules/topic/dto/index.ts

fix(dsb-client-gateway-api): update default value limit and page

---

libs/ddhub-client-gateway-frontend/ui/topics/src/lib/containers/modals/UpdateTopic/UpdateTopic.effects.ts

https://energyweb.atlassian.net/browse/AEMO-427

feat(ddhub-client-gateway-ui-topics): overwrite topic version warning

---

libs/ddhub-client-gateway-frontend/ui/channels/src/lib/containers/modals/Create/Create.effects.ts
libs/ddhub-client-gateway-frontend/ui/channels/src/lib/containers/modals/Create/Details/Details.effects.ts
libs/ddhub-client-gateway-frontend/ui/channels/src/lib/containers/modals/Create/Details/Details.tsx

https://energyweb.atlassian.net/browse/AEMO-475

fix(ddhub-client-gateway-ui-channels): hide payload encryption

---

libs/ddhub-client-gateway-frontend/ui/channels/src/lib/containers/modals/Create/Create.effects.ts
libs/ddhub-client-gateway-frontend/ui/channels/src/lib/containers/modals/Create/Details/Details.effects.ts
libs/ddhub-client-gateway-frontend/ui/channels/src/lib/containers/modals/Create/Details/Details.tsx

Reverts energywebfoundation/ddhub-client-gateway#103

Revert "fix(ddhub-client-gateway-ui-channels): hide payload encryption"

---

libs/ddhub-client-gateway-frontend/ui/topics/src/lib/components/Topics/Topics.effects.ts

https://energyweb.atlassian.net/browse/AEMO-394

feat(ddhub-client-gateway-ui-topics): export schema directly from table

---

devops/helms/ddhub-gateway-demo/values.yaml
devops/helms/ddhub-gateway-dev/values.yaml
devops/helms/ddhub-gateway-qa/values.yaml

- disable log colours
- update dev instance ws timeout and events config

Chore/ devops

---

libs/ddhub-client-gateway-frontend/ui/login/src/lib/SetUserData.effects.ts

- Issue: If participant's namespace is not `ddhub.apps.energyweb.iam.ewc`, sidebar menu will not be rendered due to `config` is not initialised first.
- Moved logic into `useEffect` to ensure `config` and `roles` to be available before checking against `routeRestrictions`.

fix(ddhub-client-gateway-ui-login): fix empty config

---

apps/dsb-client-gateway-api/src/app/modules/keys/service/keys.service.ts
apps/dsb-client-gateway-api/src/app/types/environment-variables.ts
apps/dsb-client-gateway-scheduler/src/app/modules/did/did.module.ts
apps/dsb-client-gateway-scheduler/src/app/modules/did/service/channel-did.service.ts
apps/dsb-client-gateway-scheduler/src/app/modules/keys/keys.module.ts
apps/dsb-client-gateway-scheduler/src/app/modules/keys/service/keys.service.ts
docs/api-variables.md
libs/dsb-client-gateway-iam-client/src/lib/service/iam.service.ts

1. Fixes the did cache bug (IamService only ever retrieving local client gateway's DID document).
2. Adds default value for DID_TTL (1 hour).
3. When channel qualified dids is updated, also update did document cache on client gateway.

fix(dsb-client-gateway-scheduler): fix did document cache mechanism

---

apps/dsb-client-gateway-scheduler/src/app/modules/did/service/channel-did.service.ts

Following on my PR yesterday:
1. Refactored channel-did refresh cron job to refresh all related dids, not just those from the assigned roles.

refactor: channel did cache refresh 

---

libs/ddhub-client-gateway-frontend/ui/channels/src/lib/components/ChannelInfo/ChannelInfo.tsx
libs/ddhub-client-gateway-frontend/ui/channels/src/lib/components/RestrictionsViewBox/RestrictionsViewBox.tsx

Some channels cannot be viewed due to undefined error

fix(ddhub-client-gateway-ui-channels): fix null checking

---

apps/dsb-client-gateway-api/src/app/modules/gateway/gateway.controller.ts
apps/dsb-client-gateway-api/src/app/modules/gateway/gateway.module.ts
apps/dsb-client-gateway-api/src/app/modules/health/health.controller.ts
apps/dsb-client-gateway-api/src/app/modules/health/health.module.ts
apps/dsb-client-gateway-scheduler/src/app/service/private-key-watcher.service.ts
libs/ddhub-client-gateway-tls-agent/src/lib/service/tls-agent.service.ts

For context see:
[https://energyweb.atlassian.net/browse/AEMO-515](https://energyweb.atlassian.net/browse/AEMO-515)
[https://energyweb.atlassian.net/browse/AEMO-516](https://energyweb.atlassian.net/browse/AEMO-516)

fix(dsb-client-gateway-api): fix issue with mtls certificates being used when not enabled

---

libs/ddhub-client-gateway-frontend/ui/core/src/components/form/Autocomplete/Autocomplete.styles.ts
libs/ddhub-client-gateway-frontend/ui/core/src/components/form/Autocomplete/Autocomplete.tsx
libs/ddhub-client-gateway-frontend/ui/messaging/src/lib/components/Messages/Messages.effects.tsx
libs/ddhub-client-gateway-frontend/ui/messaging/src/lib/containers/DataMessagingUpload/DataMessagingUpload.effects.ts
libs/dsb-client-gateway-api-client/src/lib/mocks/index.ts

Changes:
- Fix invalid date (nanoseconds to milliseconds)
- Apply same css class to autocomplete loading
- Fix Topic Version not cleared on change of Channel or Topic

Fix/timestampnanos UI

---

apps/dsb-client-gateway-api/src/app/modules/message/exceptions/ack-pending-not-found.exception.ts
apps/dsb-client-gateway-api/src/app/modules/message/service/message.service.ts
libs/dsb-client-gateway-errors/src/lib/dsb-client-gateway-errors.ts

handle exception from request ack (timeout,error from mb)

fix(dsb-client-gateway-api): handle exception from request ack

---

apps/dsb-client-gateway-api/src/app/modules/message/service/message.service.ts
libs/dsb-client-gateway-storage/src/lib/module/acks/entity/pending-acks.entity.ts
libs/dsb-client-gateway-storage/src/lib/module/acks/wrapper/pending-acks-wrapper.repository.ts
migrations/1668390172273-clientId-from.ts

feat(dsb-client-gateway-api): add new logic for send ack with date

---

devops/helms/ddhub-gateway-dev-1/values.yaml
devops/helms/ddhub-gateway-dev/values.yaml

> "as API and scheduler are sharing the same environment variables. secret, configmap and appConfig are merged as environment variables. this is just a workaround. in v2, we got rid of configMap. but use envVars." 
from @vickenliu

add env variable in ddhub-client-gateway dev, dev-1

---

apps/dsb-client-gateway-api/src/app/modules/message/dto/request/send-message.dto.ts

add anonymous recipients to swagger

fix(dsb-client-gateway-api): add anonymous recipients to swagger

---

libs/ddhub-client-gateway-frontend/ui/channels/src/lib/containers/modals/Create/Topics/Topics.effects.ts
libs/ddhub-client-gateway-frontend/ui/channels/src/lib/containers/modals/Create/Topics/Topics.tsx

fix(ddhub-client-gateway-ui-channels): reset topic input on add

---

apps/dsb-client-gateway-api/src/app/types/environment-variables.ts
apps/dsb-client-gateway-api/src/main.ts
apps/dsb-client-gateway-scheduler/src/app/modules/topic/service/delete-old-topics.service.ts
apps/dsb-client-gateway-scheduler/src/app/modules/topic/service/topic-refresh.service.ts
docs/api-variables.md
libs/ddhub-client-gateway-message-broker/src/lib/services/ddhub-topics.service.ts

Reverts energywebfoundation/ddhub-client-gateway#302

Revert "fix(dsb-client-gateway-api): add env var for openapi"

---

apps/dsb-client-gateway-api/src/main.ts

fix(dsb-client-gateway-api): update override when merge

Rebase on master and cherry pick last develop commit

---

libs/ddhub-client-gateway-association-keys/src/lib/service/association-keys.service.ts

fix(dsb-client-gateway-api): fix next key

---

libs/ddhub-client-gateway-utils/src/lib/services/ethers.service.ts
package-lock.json
package.json

fix ewc auth invalid token issue

fix(dsb-client-gateway-api): replace ether base64 to  base64Url,

---

apps/dsb-client-gateway-frontend/src/components/Drawer/CollapsableMenu/CollapsableMenu.tsx
apps/dsb-client-gateway-frontend/src/components/Drawer/Drawer.tsx

- Added `Message Box` menu items
- Added submenu icon

feat(dsb-client-gateway-frontend): add message box menu

---

apps/dsb-client-gateway-frontend/src/components/Drawer/Drawer.tsx
apps/dsb-client-gateway-frontend/src/components/Header/Header.tsx
apps/dsb-client-gateway-frontend/src/pages/_app.tsx
libs/ddhub-client-gateway-frontend/ui/login/src/lib/Login.effects.ts
libs/ddhub-client-gateway-frontend/ui/login/src/lib/LoginStatus/LoginStatus.effects.tsx
libs/ddhub-client-gateway-frontend/ui/login/src/lib/LoginStatus/RefreshAccountStatus/RefreshAccountStatus.tsx
libs/ddhub-client-gateway-frontend/ui/login/src/lib/UserAuthHeaders.effects.ts
libs/ddhub-client-gateway-frontend/ui/login/src/lib/UserData.effects.ts
libs/ddhub-client-gateway-frontend/ui/login/src/lib/UserDataContext.ts
libs/ddhub-client-gateway-frontend/ui/login/src/lib/check-account-status/CheckAccountStatus.effects.ts

- fix issues with sidebar not displaying routes for non-auth enabled CGW
- fixed issue where identity check would not be triggered for non-auth enabled CGW

fix(dsb-client-gateway-frontend): fix issues with sidebar display

---

apps/dsb-client-gateway-api/src/app/modules/message/dto/response/get-received-message-response.dto.ts
apps/dsb-client-gateway-api/src/app/modules/message/service/offline-messages.service.ts
libs/ddhub-client-gateway-frontend/ui/api-hooks/src/lib/messaging/getSentMessages.ts
libs/ddhub-client-gateway-frontend/ui/channels/src/lib/containers/modals/Create/Topics/Topics.tsx
libs/ddhub-client-gateway-frontend/ui/messaging/src/lib/components/MessageInfo/MessageInfo.styles.ts
libs/ddhub-client-gateway-frontend/ui/messaging/src/lib/components/MessageInfo/MessageInfo.tsx
libs/ddhub-client-gateway-frontend/ui/messaging/src/lib/containers/MessageInbox/MessageInbox.effects.ts
libs/ddhub-client-gateway-frontend/ui/messaging/src/lib/containers/MessageOutbox/MessageOutbox.effects.ts
libs/ddhub-client-gateway-frontend/ui/messaging/src/lib/containers/MessageOutbox/MessageOutbox.tsx
libs/ddhub-client-gateway-frontend/ui/messaging/src/lib/containers/modals/MessageInboxDetails/MessageInboxDetails.effects.ts
libs/ddhub-client-gateway-frontend/ui/messaging/src/lib/containers/modals/MessageInboxDetails/MessageInboxDetails.tsx
libs/ddhub-client-gateway-frontend/ui/messaging/src/lib/containers/modals/NewMessage/NewMessage.effects.ts
libs/ddhub-client-gateway-frontend/ui/messaging/src/lib/containers/modals/NewMessage/NewMessage.tsx
libs/ddhub-client-gateway-frontend/ui/messaging/src/lib/context/modals/types.ts
libs/ddhub-client-gateway-frontend/ui/messaging/src/lib/models/channel-outbox-headers.tsx
libs/ddhub-client-gateway-user-roles/src/lib/service/user-auth.service.ts
libs/dsb-client-gateway-api-client/schema.yaml
libs/dsb-client-gateway-secrets-engine/src/lib/service/service/azure-key-vault.service.ts

- added reply message
- fixed related message list
- channel/topic filtering on reply needs some thorough testing

feat: reply message

---

libs/ddhub-client-gateway-frontend/ui/core/src/components/JsonSchemaForm/widgets/DateTimeWidget.tsx

To disable seconds for `local-date-time` update `uiSchema` as follows:
```javascript
{
"uiSchema": {
"ui:order": [
...
],
"startDateTime": { // key of property in schema
"ui:options": {
"withSeconds": false // defaults to true if option not provided
}
},
"endDateTime": { // key of property in schema
"ui:options": {
"withSeconds": false // defaults to true if option not provided
}
}
},
...
}
```

feat(ddhub-client-gateway-ui-messaging): add options handling for datetime widget

---

apps/dsb-client-gateway-api/src/app/modules/address-book/address-book.controller.ts
apps/dsb-client-gateway-api/src/app/modules/address-book/dto/request/get-contact.dto.ts
apps/dsb-client-gateway-api/src/app/modules/address-book/exceptions/contact-not-found-exception.ts
libs/ddhub-client-gateway-address-book/src/lib/service/address-book.service.ts
libs/dsb-client-gateway-errors/src/lib/dsb-client-gateway-errors.ts

feat(ddhub-client-gateway): get contact by did

---

libs/dsb-client-gateway-api-client/schema.yaml

Add swagger doc to `GET /contacts/{did}`

feat(ddhub-client-gateway): add swagger doc

---

libs/ddhub-client-gateway-frontend/ui/messaging/src/lib/containers/modals/NewMessage/NewMessage.tsx
libs/ddhub-client-gateway-frontend/ui/messaging/src/lib/containers/modals/NewMessage/NewMessage.utils.ts

Auto-fill default values from schema definition

feat(ddhub-client-gateway): auto-fill default values

---

libs/ddhub-client-gateway-frontend/ui/messaging/src/lib/models/channel-inbox-headers.tsx
libs/ddhub-client-gateway-frontend/ui/messaging/src/lib/models/message-headers.ts
libs/dsb-client-gateway-secrets-engine/src/lib/exceptions/invalid-engine.exception.ts

Also saw another issue last week when i was going through errors so I added `Azure` as valid value when reported by secrets engine exception.

fix: add chaining to determine if expected value is not undefined

---

apps/dsb-client-gateway-api/src/app/modules/utils/filter/all-exceptions.filter.ts
apps/dsb-client-gateway-frontend/src/components/BrokerCard/BrokerCard.tsx
apps/dsb-client-gateway-frontend/src/components/Scheduler/Scheduler.tsx
apps/dsb-client-gateway-frontend/src/pages/_app.tsx
libs/ddhub-client-gateway-frontend/ui/api-hooks/src/lib/scheduler/getScheduler.ts
libs/ddhub-client-gateway-frontend/ui/core/src/components/common/Badge/Badge.styles.ts
libs/ddhub-client-gateway-frontend/ui/core/src/components/common/Badge/Badge.tsx
libs/ddhub-client-gateway-frontend/ui/login/src/lib/UserData.effects.ts
libs/ddhub-client-gateway-frontend/ui/login/src/lib/UserDataContext.ts
libs/ddhub-client-gateway-frontend/ui/login/src/lib/check-account-status/CheckAccountStatus.effects.ts
libs/ddhub-client-gateway-message-broker/src/lib/services/ddhub-health.service.ts
libs/ddhub-client-gateway-tls-agent/src/lib/service/tls-agent.service.ts
libs/ddhub-client-gateway-utils/src/lib/axios.interceptor.ts
libs/dsb-client-gateway-secrets-engine/src/lib/service/service/aws-secrets-manager.service.ts
libs/dsb-client-gateway-secrets-engine/src/lib/service/service/azure-key-vault-engine.spec.ts
libs/dsb-client-gateway-secrets-engine/src/lib/service/service/azure-key-vault.service.ts
libs/dsb-client-gateway-secrets-engine/src/lib/service/service/vault.service.ts

Changes:
**Backend**
- Remove access of properties of undefined response value
- Fix certificate update flow for Azure KV, purge deleted secrets if soft delete is enabled
- Add early returns when user auth is not enabled
- Cleaned up logging
**Frontend**
- Add mTLS valid badge when mTLS is enabled
- Only show Dashboard and Gateway Settings routes in sidebar if mTLS certs are not configured
- Return to initial page (login / set private key page) if identity check returns non-200 response

fix(dsb-client-gateway-api): fix flow for mtls setup on new cgw

---

apps/dsb-client-gateway-frontend/src/pages/_app.tsx

chore(dsb-client-gateway-frontend): trigger frontend build

---

libs/ddhub-client-gateway-frontend/ui/api-hooks/src/lib/clientIds/removeClientId.ts
libs/ddhub-client-gateway-frontend/ui/login/src/lib/UserAuthHeaders.effects.ts

Encode GET request query params in Axios interceptor. Also added encoding in DELETE client

chore(dsb-client-gateway-frontend): encode query params

---

libs/ddhub-client-gateway-frontend/ui/core/src/components/Steps/Step/stepTypes.ts
libs/ddhub-client-gateway-frontend/ui/core/src/components/Steps/Steps.tsx
libs/ddhub-client-gateway-frontend/ui/roles/src/lib/components/RoleInformation/RoleInformation.tsx
libs/ddhub-client-gateway-frontend/ui/roles/src/lib/components/ScrollableBox/ScrollableBox.ts
libs/ddhub-client-gateway-frontend/ui/roles/src/lib/components/SelectRoles/SelectRoles.tsx
libs/ddhub-client-gateway-frontend/ui/roles/src/lib/containers/modals/RequestRole/RequestRole.effects.ts
libs/ddhub-client-gateway-frontend/ui/roles/src/lib/containers/modals/RequestRole/RequestRole.styles.ts
libs/ddhub-client-gateway-frontend/ui/roles/src/lib/containers/modals/RequestRole/RequestRole.tsx
libs/ddhub-client-gateway-frontend/ui/roles/src/lib/containers/modals/RequestRole/Steps/RoleDetails.tsx
libs/ddhub-client-gateway-frontend/ui/roles/src/lib/containers/modals/RequestRole/Steps/requestSteps.tsx

fixes:
AEMO-748 AEMO-749 AEMO-750 AEMO-751 AEMO-752 AEMO-753 AEMO-754 AEMO-755 AEMO-756 AEMO-757

fix: bugfixes and improvements for request roles UI
